version: 2
jobs:

  
  deploy:
    working_directory: ~/circulate
    docker:
      - image: google/cloud-sdk
    environment:
      #ES_GRAPH_URL gets substituted by our CI for production
      GOOGLE_PROJECT_ID: open-targets-library
      ES_MAIN_URL: 'http://es-200617-101804.es-200617-101804.il4.europe-west1.lb.open-targets-library.internal:9200'
    steps:
      - checkout
      - run:
          name: install jq & envsubst
          command: apt-get install -y jq gettext-base && jq --version

      - run:
          name: Decode Google Cloud Credentials
          command: echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
      - run:
          name: Authenticate to Google Cloud
          command: |
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json

      - run:
          name: Make an app.yaml
          command: |
            #make it available
            echo -e "\n\n### Substituting the ES_URL into the app.yaml \n\n"
            envsubst < app.template.yaml > app.yaml
            cat app.yaml

      - run:
          name: Deploy branch to google AppEngine (promote if it is a Tag deploy)
          no_output_timeout: 30m
          command: |
            if [ -n "${CIRCLE_TAG:+1}" ]; then
              echo -e "deploying tag ${CIRCLE_TAG}"
              gcloud app deploy --version $CIRCLE_TAG --project ${GOOGLE_PROJECT_ID}
            elif [ -n "${CIRCLE_BRANCH:+1}" ]; then
              ## branch tag and push
              echo -e "deploying branch ${CIRCLE_BRANCH} for testing"
              gcloud app deploy --no-promote --version $CIRCLE_BRANCH --project ${GOOGLE_PROJECT_ID}
            else
              echo -e "### No CIRCLE_TAG or CIRCLE_BRANCH defined"
              exit 1
            fi

  stop-instance:
    working_directory: ~/circulate
    docker:
      - image: google/cloud-sdk
    environment:
      GOOGLE_PROJECT_ID: open-targets-library
    steps:
      - run:
          name: Decode Google Cloud Credentials
          command: echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
      - run:
          name: Authenticate to Google Cloud
          command: |
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run:
          name: Stop running version
          command: |
            gcloud --project ${GOOGLE_PROJECT_ID} app versions stop $CIRCLE_BRANCH --service=default





workflows:
  version: 2
  deploy-and-test:
    jobs:
      # This is really confusing: check https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
      # - For a branch push unaffected by any filters, CircleCI runs the job.
      # - For a tag push unaffected by any filters, CircleCI skips the job.
      # - a job must have a filters tags section to run as a part of a tag push
      # - all its transitively dependent jobs must also have a filters tags
      # Also see https://discuss.circleci.com/t/build-required-steps-automatically-for-tag-filtered-workflows/15185

      - deploy:
          filters:
            tags:
              only: /^prod.*/

